"""
AI Ready Mobile — output assembly layer.

VERBATIM EXTRACT from the private AI_Ready repo's app.py (the Gold Master +
combined-output machinery), so mobile output format matches the desktop app
exactly. Source of truth is app.py — when these functions change there,
re-extract here (see CLAUDE.md sync rule).

Extracted spans (app.py line ranges as of v1.3.26): 129-326 constants +
helpers (_LEGAL_DISCLAIMER/_WORKING_NOTES_BLOCK/_APPEND_MARKER/_doc_order_key/
preamble constants + markers/_masking_rule/_mask_label/_global_rules/
_front_matter/_compute_sha256/_make_slug), 328-821 _assemble_gold_master,
856-904 _term_to_regex/_apply_custom_variables, 993-1079 registry/group
helpers + _simple_combined, 1091-1172 _PART_TARGET/_split_gold_master,
1174-1314 _emit_combined_group. Only edits: this header, imports,
OUTPUTS_DIR/VERSION module globals (set by mobile.py at runtime),
overlap-note stub.
"""
import hashlib
import json
import os
import re
from datetime import datetime

OUTPUTS_DIR = "/outputs"          # Pyodide MEMFS; mobile.py ensures it exists
VERSION = "mobile"                # set by mobile.py from the web app version


def _check_builtin_overlap(term: str) -> str:   # desktop UI hint — not used on mobile
    return ""

_LEGAL_DISCLAIMER = (
    "> **⚠ LEGAL NOTICE:** AI Ready and any AI system analyzing this document can make mistakes. "
    "All data, figures, and content extracted or derived in this document must be independently "
    "validated against the original source files before use in any decision, legal proceeding, "
    "tax filing, financial transaction, or professional context. "
    "This document is a processing artifact and does not constitute legal, financial, tax, or professional advice."
)

# Living-document support: a combined/topic MD is meant to GROW over time. Sources are
# ordered NEWEST-FIRST, so the document leads with the most recent material and new
# documents are appended at the TOP (just below the working notes). The user keeps
# running notes at the top; both zones are explicitly marked so manual edits are safe
# and the AI knows to read them.
_WORKING_NOTES_BLOCK = (
    "## 📌 Working notes — YOURS to edit (the AI reads this first)\n\n"
    "> This is a **living document for this topic**, ordered **newest first**: add your "
    "running summary, context, key dates, or questions here. New source documents go on "
    "**top** — paste each new (newer) document just below the append marker right after "
    "these notes. The block below is yours.\n\n"
    "<!-- BEGIN WORKING NOTES — edit freely -->\n\n"
    "_(add your notes for this topic here)_\n\n"
    "<!-- END WORKING NOTES -->\n\n---\n\n"
)
# Placed at the TOP of the source region (right after the working notes) so newly
# appended documents become the newest entry, on top — keeping the file newest-first.
_APPEND_MARKER = (
    "<!-- =============================================================\n"
    "  ⬆ APPEND NEW (NEWER) SOURCE DOCUMENTS IMMEDIATELY BELOW THIS MARKER\n"
    "  This file is ordered NEWEST-FIRST, so new material goes on TOP:\n"
    "  1. Run the new document through AI Ready by itself.\n"
    "  2. From its output file, COPY everything FROM the `# ===== START FILE: ... =====`\n"
    "     line DOWN TO the `# ===== END FILE: ... =====` line (skip the `---` metadata\n"
    "     block at the very top — that belongs to standalone files only) and paste it\n"
    "     right below this marker. It becomes the newest entry, on top.\n"
    "  3. Update your Working Notes above.\n"
    "  ============================================================= -->\n"
)


def _doc_order_key(name: str):
    """Sort key for ordering source documents NEWEST-FIRST. Extracts a date
    (`YY`/`YYYY` then `MM` then `DD`, separated by `.`/`-`/`_`/`/`) from anywhere in the
    filename or relative path; dated files come first, ordered newest→oldest, and
    undated files follow in name order. Heuristic — relies on the date-in-name
    convention; names without a recognizable date just fall back to alphabetical."""
    m = re.search(r'(?<!\d)((?:19|20)?\d{2})[.\-_/](\d{1,2})[.\-_/](\d{1,2})(?!\d)',
                  name or "")
    if m:
        y, mo, d = m.group(1), m.group(2), m.group(3)
        if len(y) == 2:
            y = "20" + y
        try:
            val = int(y) * 10000 + int(mo) * 100 + int(d)
            return (0, -val, name or "")     # dated first, newest (largest) first
        except ValueError:
            pass
    return (1, 0, name or "")                 # undated last, by name

_AI_PREAMBLE_HEAD = (
    "> **⚙ FOR AI ASSISTANTS — READ BEFORE RESPONDING:**\n"
    ">\n"
    "> This is a Gold Master file generated by AI Ready. It contains verbatim text extracted from one or more "
    "original source documents. Follow these rules on every response:\n"
    ">\n"
    "> **1. Section 3 is the authoritative source.** All answers must be grounded in Section 3 content. "
    "Do not infer, estimate, or summarize beyond what Section 3 states.\n"
    ">\n"
    "> **2. Always cite the source page.** When referencing any value, finding, result, or statement, "
    "cite the page anchor — e.g. `[p.3](#src01-filename-page-003)`. "
    "If the user asks where something came from, provide the anchor link.\n"
    ">\n"
    "> **3. Flag abnormal values.** If Section 3 contains lab results, measurements, or findings marked "
    "as High, Low, Abnormal, or outside a reference range, proactively flag these when relevant to the question.\n"
)

_AI_PREAMBLE_TAIL = (
    ">\n"
    "> **5. Multi-source files.** If this file contains multiple source documents (SRC-001, SRC-002, etc.), "
    "identify which source each answer comes from and cite its anchor prefix.\n"
    ">\n"
    "> **6. Reading a fragment (retrieved excerpt).** In a knowledge library you may see only a slice of "
    "this file, without this header. Every page heading names its source document "
    "(“Page 12 — contract.pdf”) and every page anchor id encodes source + page "
    "(“src07-contract … 012”): attribute and cite from those even when this header is not "
    "visible, and never assume an excerpt is the whole document.\n"
    ">\n"
    "> **7. This is not medical, legal, or financial advice.** Always recommend the user verify against "
    "original source documents and consult qualified professionals for decisions."
)

# Markers used when a Gold Master is assembled WITHOUT its global preamble (the
# combined-output path): the per-file output replaces them with the real rules/
# notice text so standalone files stay self-contained, while combined files carry
# the rules ONCE per part instead of once per document (capacity + retrieval noise).
_MARK_RULES = "<!-- AIR:RULES -->"
_MARK_NOTICE = "<!-- AIR:NOTICE -->"
_RULES_POINTER = (
    "> *AI instructions and the legal notice for this document are at the top of this combined file.*"
)


def _global_rules(mask_mode: str, skip_all_masking: bool = False) -> str:
    """The document-type-independent AI rules block (rules 1–7). Type-specific
    rule 8 (tax/medical/document-index) stays with each document."""
    return _AI_PREAMBLE_HEAD + _masking_rule(mask_mode, skip_all_masking) + _AI_PREAMBLE_TAIL


def _masking_rule(mask_mode: str, skip_all_masking: bool = False) -> str:
    """Rule 4 of the AI preamble, stated ACCURATELY for THIS file's masking — so an
    unmasked file is never described as redacted (the old static rule always said
    'Respect masking', which was wrong on a no-mask run). Unmasked files say so plainly,
    so neither a human nor an AI mistakes a real value for a redaction; masked files keep
    the do-not-reconstruct instruction and name the mode."""
    if skip_all_masking or mask_mode == "none":
        return (
            ">\n"
            "> **4. This file is UNMASKED.** No redaction was applied — every name, date, number, "
            "and identifier in Section 3 is the **real, verbatim value** from the source. There are "
            "no `[… MASKED]` placeholders here; treat all values as authoritative.\n"
        )
    label = "full" if mask_mode == "full" else "soft"
    return (
        ">\n"
        f"> **4. This file is MASKED ({label} mask).** Some values were intentionally redacted and "
        "appear as `[DOB MASKED]`, `[SSN MASKED]`, `[NAME MASKED]`, or similar. Do not attempt to "
        "infer or reconstruct them.\n"
    )


def _mask_label(mask_mode: str, skip_all_masking: bool = False) -> str:
    """Short, human-clear masking status for metadata rows and headers, so a file in a
    mixed library (some masked, some not) is unambiguous at a glance."""
    if skip_all_masking or mask_mode == "none":
        return "none — UNMASKED (all values verbatim from source)"
    return f"{mask_mode} — MASKED"


def _front_matter(kind: str, fields: list) -> str:
    """Machine-readable YAML front matter for every output file (tooling can
    parse provenance without regex; AI assistants read it as plain metadata).
    Values are JSON-encoded, which is valid YAML and handles quotes/colons in
    filenames safely."""
    lines = ["---", f"kind: {kind}"]
    for key, value in fields:
        lines.append(f"{key}: {json.dumps(value, ensure_ascii=False)}")
    lines += ["---", ""]
    return "\n".join(lines) + "\n"

# Appended only for Tax Form documents (the only type with a Tax Line Index).
_AI_PREAMBLE_TAX = (
    "\n>\n"
    "> **8. Tax Line Index integrity.** Values in the Tax Line Index (Section 1) are extracted verbatim "
    "from the source document — never computed, estimated, or derived. "
    "When answering tax questions, cite both the Tax Line Index entry AND the source page anchor in Section 3. "
    "Do not calculate or derive values not explicitly present in the source."
)

# Appended only for Medical Document types (the only type with a Medical Value Index).
_AI_PREAMBLE_MEDICAL = (
    "\n>\n"
    "> **8. Medical Value Index integrity.** Values in the Medical Value Index (Section 1) are extracted "
    "verbatim from the source report — never computed, estimated, or interpreted. Each row is a single "
    "test/result with its units, reference range, and any abnormal flag (H/L/Critical) exactly as printed. "
    "When answering, cite both the index entry AND the source page anchor in Section 3, and surface any "
    "abnormal flag. The index lists only values AI Ready could read with high confidence — treat it as "
    "incomplete, never as a complete result set, and do not infer a normal/absent result from omission. "
    "Provide no diagnosis or medical advice; this is a reference extraction, not clinical guidance."
)

# Appended for any document carrying a Document Index (the universal text/structure
# audit index — legal, LLC, insurance, financial, generic, etc.).
_AI_PREAMBLE_LEGAL = (
    "\n>\n"
    "> **8. Document Index integrity.** Entries in the Document Index (Section 1) — parties, dates, amounts, "
    "defined terms, numbered references (e.g. Section 9.4, Article XI, a statute or case citation), section/"
    "exhibit headings, and case numbers — are read verbatim from the source and each links to the page in "
    "Section 3 where it appears. Use the index to navigate and to cite the exact source page and reference "
    "number; quote the actual clause/provision wording from the verbatim Section 3 text, never paraphrased "
    "from the index. The index is a navigation aid and is NOT guaranteed complete — do not infer that a term, "
    "party, clause, or obligation is absent because it is not indexed. Provide no legal or professional advice; "
    "this is a reference extraction."
)


def _compute_sha256(file_path: str) -> str:
    h = hashlib.sha256()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _make_slug(filename: str, source_idx: int) -> str:
    """Create a URL-safe, source-specific anchor prefix from a filename and 1-based index."""
    stem = os.path.splitext(filename)[0]
    slug = re.sub(r'[^a-z0-9]+', '-', stem.lower()).strip('-')[:24].rstrip('-')
    return f"src{source_idx:02d}-{slug}"

def _assemble_gold_master(
    filename: str, meta: dict, sha256_hash: str, mask_mode: str,
    process_date: str, section3_md: str,
    file_slug: str = "", skip_all_masking: bool = False,
    condense_report: dict | None = None,
    include_preamble: bool = True
) -> str:
    content_type = meta.get("content_type", "Document")
    form = meta.get("form", "")
    form_name = meta.get("form_name", "")
    tax_year = meta.get("tax_year", "")
    tax_period = meta.get("tax_period", "")
    transcript_date = meta.get("transcript_date", "")
    page_count = meta.get("page_count", "?")
    titles = meta.get("potential_titles", [])
    doc_title = titles[0] if titles else filename
    author = meta.get("author", "")
    case_numbers = meta.get("case_numbers", [])
    sheets = meta.get("sheets", [])

    anchor_prefix = re.escape(file_slug) if file_slug else "page"
    extracted_pages = len(re.findall(rf'<a id="{anchor_prefix}-page-\d+"', section3_md))

    # RAG self-identification: suffix every page/slide heading with the source
    # filename so a retrieved CHUNK of a knowledge library names its document
    # ("### Page 12" alone is ambiguous across a multi-document library). Keyed
    # on the converter-generated anchor (optionally followed by Bates/blockquote
    # annotation lines) so verbatim source text that happens to start with "###"
    # is never touched. Anchors themselves are unchanged.
    section3_md = re.sub(
        rf'(<a id="{anchor_prefix}-page-\d+[^"]*"></a>(?:\s*\n>[^\n]*)*\s*\n+)(###[^\n]+)',
        lambda m: m.group(1) + m.group(2) + f" — {filename}",
        section3_md)

    image_only = section3_md.count("image-only or scanned page")
    unextractable = section3_md.count("No extractable text after filtering")
    anchors_unique = "Yes — source-specific prefix" if file_slug else "No — generic (single-file mode)"
    anchor_example = f"#{file_slug}-page-001" if file_slug else "#page-001"

    meta_rows = [
        f"| Source File | `{filename}` |",
        f"| Document Title | {doc_title} |",
        f"| Content Type | {content_type} |",
    ]
    if form:
        form_display = form + (f" — {form_name}" if form_name else "")
        meta_rows.append(f"| Form | {form_display} |")
    # Only show tax year/period for actual tax documents — prevents birth years
    # in medical records from appearing as false "Tax Year" metadata
    is_tax_doc = content_type == "Tax Form"
    if is_tax_doc and tax_period:
        meta_rows.append(f"| Tax Period | {tax_period} |")
    elif is_tax_doc and tax_year:
        meta_rows.append(f"| Tax Year | {tax_year} |")
    if transcript_date:
        meta_rows.append(f"| Transcript Date | {transcript_date} |")
    if author:
        meta_rows.append(f"| Author | {author} |")
    if case_numbers:
        meta_rows.append(f"| Case Numbers | {', '.join(case_numbers)} |")
    if sheets:
        label = "Sheets" if len(sheets) > 1 else "Sheet"
        meta_rows.append(f"| {label} | {', '.join(str(s) for s in sheets)} |")
    meta_rows += [
        f"| Pages / Sheets / Rows | {page_count} |",
        f"| [SHA-256](https://en.wikipedia.org/wiki/SHA-2) | `{sha256_hash}` |",
        f"| Mask Mode | {_mask_label(mask_mode, skip_all_masking)} |",
        f"| Processed | {process_date} |",
        f"| Generated By | AI Ready {VERSION} |",
    ]

    scanned_ratio = meta.get("scanned_ratio", 0)
    scanned_warning = ""
    if scanned_ratio >= 0.5:
        scanned_warning = f" ⚠ {int(scanned_ratio*100)}% of pages are scanned images — text extraction incomplete"

    validation_rows = [
        f"| Source pages reported | {page_count} |",
        f"| Anchored sections extracted | {extracted_pages} |",
        f"| Image-only / unextractable pages | {image_only + unextractable}{scanned_warning} |",
        f"| Page anchors unique (combined file) | {anchors_unique} |",
        f"| SHA-256 recorded | Yes |",
    ]
    deduped = meta.get("deduped_pages", 0)
    if deduped:
        validation_rows.append(
            f"| Duplicate pages collapsed | {deduped} byte-identical copies replaced "
            f"with a pointer to the first (anchors preserved; no data lost) |")

    # Source-data integrity — confirm numeric values survived extraction unchanged.
    integ = meta.get("integrity") or {}
    if integ.get("total"):
        if integ.get("ok"):
            integ_val = f"✓ PASS — all {integ['total']} source values confirmed present in extraction"
        else:
            ex = ", ".join(str(x) for x in integ.get("missing", [])[:8])
            integ_val = (f"⚠ REVIEW — {integ['missing_count']} of {integ['total']} source values "
                         f"({integ.get('pct', 0)}% preserved) could not be confirmed in the extraction"
                         + (f" (e.g. {ex})" if ex else "")
                         + ". Verify these against the source before relying on them.")
        validation_rows.append(f"| Source-data integrity (values & dates) | {integ_val} |")

    # OCR confidence — the integrity signal for SCANNED pages, where numeric-token
    # integrity cannot apply (no digital text layer to compare). Surfaced so the
    # scanned content carries a verifiable quality score, not silent uncertainty.
    ocr_conf = meta.get("ocr_confidence")
    if ocr_conf:
        low = ocr_conf.get("low_pages", 0)
        ocr_val = (f"{'✓' if low == 0 else '⚠'} {ocr_conf['pages']} scanned page(s) read by OCR — "
                   f"mean confidence {ocr_conf['mean']}%, lowest {ocr_conf['min']}%"
                   + (f"; **{low} page(s) flagged for review** (low mean confidence, or a "
                      f"load-bearing word misread on an otherwise-clean page) — verify those "
                      f"against the original" if low else ". Spot-check values against the original."))
        validation_rows.append(f"| OCR confidence (scanned-page integrity) | {ocr_val} |")

    # Per-page reference labels — Bates stamps or court-record "C-pages", tied to
    # THIS file. Surfaced so an AI knows the scheme and can navigate to a label
    # (each page's label is annotated after its anchor in Section 3 and indexed).
    bates = meta.get("bates")
    if bates and bates.get("start"):
        term = bates.get("label_term", "Bates No.")
        row_label = "Bates numbering" if bates.get("kind") == "Bates" else "Record-page labels"
        validation_rows.append(
            f"| {row_label} | **{bates['start']} – {bates['end']}** · "
            f"{bates['count']} pages · 1 per page. Ask for a {term} to navigate; "
            f"each page's label is shown after its page anchor in Section 3. |")

    # Tax Line Index — for Tax Form documents only
    # Provides AI-queryable structured table: Tax Year, Form, Line, Value, Source Page
    tax_line_index = meta.get("tax_line_index", [])
    tax_line_section = []
    if content_type == "Tax Form" and tax_line_index and not meta.get("tax_index_reliable", True):
        # Safety net: the extractor produced figures, but they failed form
        # arithmetic — the layout isn't one AI Ready can parse reliably. Withhold
        # the figures rather than present confident wrong tax numbers.
        form_display = meta.get("form", "Tax Form")
        tax_year_display = meta.get("tax_year") or meta.get("tax_period") or "?"
        tax_line_section = [
            "",
            "### Tax Line Index",
            "",
            f"> **⚠ TAX LINE INDEX WITHHELD — UNRELIABLE EXTRACTION.** "
            f"AI Ready could not reliably read structured line values from this "
            f"document's layout (Form: **{form_display}** · Tax Year: **{tax_year_display}**). "
            f"{meta.get('tax_index_unreliable_reason', '')} "
            f"**No structured figures are listed here, on purpose** — presenting them "
            f"would risk confident but wrong tax numbers. Use the verbatim text in "
            f"Section 3 and the original PDF as the authoritative record.",
            "",
        ]
    elif content_type == "Tax Form" and tax_line_index:
        form_display = meta.get("form", "Tax Form")
        tax_year_display = meta.get("tax_year") or meta.get("tax_period") or "?"
        # Completeness caveat — if any page could not be read (image-only /
        # unextractable), say so plainly so an omitted value is never mistaken for
        # a blank line.
        unread_pages = image_only + unextractable
        if unread_pages:
            unread_note = (
                f" **⚠ {unread_pages} page(s) in this document could not be read "
                f"(image-only or unextractable) — any tax line on those pages is "
                f"MISSING from this index. See Section 3 and the original PDF.**"
            )
        else:
            unread_note = ""
        tax_line_section = [
            "",
            "### Tax Line Index",
            "",
            f"> **Source-extracted values only. No derivation, estimation, or summarization.** "
            f"Every value in this table is read verbatim from the source document `{filename}`. "
            f"Tax Year: **{tax_year_display}** · Form: **{form_display}**. "
            f"Source page links point to the exact page in Section 3 where the value appears.",
            "",
            f"> **⚠ Completeness is NOT guaranteed.** This index lists only line values "
            f"AI Ready could read with high confidence. A line that is blank, $0, or whose "
            f"value could not be confidently read from the PDF is **omitted** here — an "
            f"omission does NOT mean the line is empty. Always verify both the figures AND "
            f"completeness against Section 3 and the original document before use.{unread_note}",
            "",
            "| Tax Year | Form | Line | Description | Column | Value | Source Page |",
            "|---|---|---|---|---|---|---|",
        ]
        for entry in tax_line_index[:600]:   # cap generously — every form line + grid cell
            desc = entry.get("description") or "—"
            col = entry.get("column") or "—"   # grid forms (Sch E etc.) set this; 1040 leaves it blank
            tax_line_section.append(
                f"| {entry.get('tax_year','?')} | {entry.get('form','?')} | "
                f"{entry.get('line','?')} | {desc} | {col} | "
                f"{entry.get('value','?')} | {entry.get('page','—')} |"
            )
        tax_line_section.append("")

    # Medical Value Index — for Medical Document types only. The analog of the
    # Tax Line Index: every discrete clinical test/result, traceable to a source
    # page, abnormal results flagged. Withholds (rather than guess) on narrative,
    # graphical, or reference-text layouts it cannot parse confidently.
    med_index = meta.get("medical_value_index", [])
    med_value_section = []

    def _cell(s):
        return str(s or "").replace("|", "\\|").strip() or "—"

    if content_type == "Medical Document" and not meta.get("medical_index_reliable", True):
        med_value_section = [
            "",
            "### Medical Value Index",
            "",
            f"> **ℹ NO STRUCTURED VALUE INDEX FOR THIS DOCUMENT.** "
            f"{meta.get('medical_index_unreliable_reason', '')} "
            f"This is expected for narrative reports (radiology, pathology, clinical "
            f"notes), graphically-plotted panels, and reference material. The verbatim "
            f"text in Section 3 and the original PDF are the authoritative record.",
            "",
        ]
    elif content_type == "Medical Document" and med_index:
        abnormal = sum(1 for e in med_index if e.get("flag"))
        unread_pages = image_only + unextractable
        unread_note = (
            f" **⚠ {unread_pages} page(s) could not be read (image-only or "
            f"unextractable) — any value on those pages is MISSING from this index.**"
            if unread_pages else ""
        )
        med_value_section = [
            "",
            "### Medical Value Index",
            "",
            f"> **Source-extracted clinical values only. No derivation, estimation, or "
            f"interpretation.** Every test and result below is read verbatim from "
            f"`{filename}` and links to the source page in Section 3. "
            f"{abnormal} value(s) carry an abnormal flag (H/L/Critical) as marked in the source.",
            "",
            f"> **⚠ Completeness is NOT guaranteed.** This index lists only discrete "
            f"values AI Ready could read with high confidence (test name paired with a "
            f"result and units or a reference range). A value rendered as a chart/graphic, "
            f"embedded in narrative prose, or whose result could not be confidently read "
            f"is **omitted** — an omission does NOT mean the test is absent. Always verify "
            f"figures AND completeness against Section 3 and the original document.{unread_note}",
            "",
            "| Panel | Test | Result | Units | Reference Range | Flag | Source Page |",
            "|---|---|---|---|---|---|---|",
        ]
        for e in med_index[:1500]:
            page_link = f"[p.{e['page']}](#{e['anchor']})" if e.get("anchor") else f"p.{e.get('page','—')}"
            med_value_section.append(
                f"| {_cell(e.get('panel'))} | {_cell(e.get('test'))} | "
                f"{_cell(e.get('result'))} | {_cell(e.get('units'))} | "
                f"{_cell(e.get('ref_range'))} | {_cell(e.get('flag'))} | {page_link} |"
            )
        med_value_section.append("")

    # Document Index — the UNIVERSAL audit fingerprint. Shown for every document
    # whose format is text (i.e. that does not already have a reliable tabular
    # row/column index — tax line index or medical value index). The decision is by
    # FORMAT, not document type: a tabular form gets its grid index; everything else
    # — legal, LLC, insurance, financial statements, generic PDFs, and any tax/
    # medical doc whose tabular index was withheld — gets this. So a misclassified
    # document is never left unaudited. Indexes the auditable elements (parties,
    # dates, amounts, defined terms, numbered references/clauses/statutes/citations,
    # section/exhibit headings, case numbers), each traceable to its source page.
    legal_index = meta.get("legal_index", [])
    _has_tabular = (
        (content_type == "Tax Form" and tax_line_index and meta.get("tax_index_reliable", True))
        or (content_type == "Medical Document" and med_index and meta.get("medical_index_reliable", True))
    )
    _show_doc_index = not _has_tabular
    legal_index_section = []
    if _show_doc_index and not meta.get("legal_index_reliable", False):
        legal_index_section = [
            "",
            "### Document Index",
            "",
            f"> **ℹ NO STRUCTURED INDEX FOR THIS DOCUMENT.** "
            f"{meta.get('legal_index_unreliable_reason', '')} "
            f"The verbatim text in Section 3 and the original document are the "
            f"authoritative record.",
            "",
        ]
    elif _show_doc_index and legal_index:
        kinds = {}
        for e in legal_index:
            kinds[e["kind"]] = kinds.get(e["kind"], 0) + 1
        summary_bits = ", ".join(f"{v} {k.lower()}{'s' if v != 1 and not k.endswith('.') else ''}"
                                 for k, v in sorted(kinds.items()))
        legal_index_section = [
            "",
            "### Document Index",
            "",
            f"> **Source-extracted, page-traceable elements only — no interpretation.** "
            f"Every entry below is read verbatim from `{filename}` and links to the "
            f"source page in Section 3, making this document searchable and "
            f"auditable. Indexed: {summary_bits}.",
            "",
            f"> **⚠ Completeness is NOT guaranteed.** This index surfaces the auditable "
            f"elements AI Ready could extract with confidence. It is a navigation aid — "
            f"the verbatim Section 3 text and the original document remain authoritative. "
            f"Verify against Section 3.",
            "",
            "| Element | Detail | Value | Source Page |",
            "|---|---|---|---|",
        ]
        for e in legal_index[:800]:
            page_link = f"[p.{e['page']}](#{e['anchor']})" if e.get("anchor") else f"p.{e.get('page','—')}"
            legal_index_section.append(
                f"| {_cell(e.get('kind'))} | {_cell(e.get('detail'))} | "
                f"{_cell(e.get('value'))} | {page_link} |"
            )
        legal_index_section.append("")

    # Condensation Report — the audit trail when Large / Custom Project condense mode
    # ran. States exactly what was kept vs collapsed and which boilerplate was removed,
    # so nothing is hidden: every collapsed page keeps its anchor + Bates No. (the
    # Document Index above still resolves to it), and the full verbatim text is one
    # re-run away (toggle OFF). Listed in Section 1 alongside the indexes.
    condense_section = []
    if condense_report:
        r = condense_report
        boiler = r.get("boilerplate", [])
        boiler_lines = [f"> - `{_cell(ln)}` — removed from {c} page(s)" for ln, c in boiler[:12]]
        if r.get("mode") == "transcript":
            # Safe tightening — testimony kept whole, scaffolding tightened.
            condense_section = [
                "",
                "### Condensation Report",
                "",
                f"> **ℹ THIS FILE WAS CONDENSED — TRANSCRIPT, SAFELY TIGHTENED (Large / "
                f"Custom Project mode).** This was detected as a deposition/hearing "
                f"transcript, so **all {r['pages_total']} pages and every word of "
                f"testimony are kept verbatim** — testimony is never collapsed. Line "
                f"numbers are preserved (so \"page N, line M\" still cites); only the "
                f"line-number scaffolding was inlined ({r.get('lines_inlined', 0)} line(s)) "
                f"and repeated page headers/footers removed, to shrink the file losslessly.",
                "",
            ]
            if boiler_lines:
                condense_section += [
                    "> **Repeated header/footer removed** (noted once):",
                ] + boiler_lines + [""]
        elif r.get("pages_collapsed"):
            # Collapse of reproduced third-party news/newsletter pages only.
            ranges = r.get("collapsed_ranges", [])
            range_rows = []
            for lo, hi, blo, bhi in ranges[:300]:
                bates_span = f"{blo} – {bhi}" if blo and bhi else "—"
                anchor = f"{file_slug}-page-{lo:03d}" if file_slug else f"page-{lo:03d}"
                range_rows.append(f"| [p.{lo}](#{anchor}) – p.{hi} | {bates_span} | {hi - lo + 1} |")
            keep_applied = r.get("keep_ranges_applied", [])
            condense_section = [
                "",
                "### Condensation Report",
                "",
                f"> **ℹ THIS FILE WAS CONDENSED (Large / Custom Project mode).** "
                f"**{r['pages_kept']} of {r['pages_total']}** pages are kept **verbatim — "
                f"including ALL case evidence, untouched.** Only **{r['pages_collapsed']}** "
                f"page(s) **positively identified as reproduced third-party filler** — news/"
                f"press-clipping digests, automated/no-reply marketing email, or a reproduced "
                f"reference manual (not case evidence) — had their body collapsed to a one-line "
                f"marker. **No page was deleted:** every collapsed page keeps its anchor and "
                f"Bates No. (listed below), so the Document Index above still maps to it, it "
                f"stays findable, and you can pull it to prove it is filler. **For the full "
                f"text, re-run with the Large / Custom Project toggle OFF.**",
                "",
            ]
            if keep_applied:
                condense_section += [
                    f"> **Force-kept verbatim** by your Bates/page request: "
                    f"{len(keep_applied)} page(s).", ""]
            if range_rows:
                condense_section += [
                    "> Collapsed news/newsletter ranges (everything else is verbatim):",
                    "",
                    "| Collapsed pages | Bates span | Count |",
                    "|---|---|---|",
                ] + range_rows + [""]

    # Scanned document alert — adapted based on whether OCR was available
    scanned_alert = []
    ocr_pages = meta.get("ocr_pages", 0)
    ocr_available = meta.get("ocr_available", False)
    if scanned_ratio >= 0.5:
        pct = int(scanned_ratio * 100)
        if ocr_pages > 0:
            scanned_alert = [
                "",
                f"> **ℹ OCR APPLIED — {pct}% OF PAGES WERE SCANNED IMAGES**",
                ">",
                f"> This document (`{filename}`) contained scanned images. "
                f"AI Ready processed {ocr_pages} page(s) using Optical Character Recognition (OCR) at 300 DPI. "
                f"Pages processed via OCR are marked **Page N (OCR)** in Section 3.",
                ">",
                "> **What this means for AI analysis:**",
                "> - OCR text is generally accurate but may contain errors on low-contrast, handwritten, or damaged scans",
                "> - Verify critical values (policy numbers, dollar amounts, dates) against the original document",
                "> - Pages marked (OCR) carry slightly lower confidence than digitally-created pages",
            ]
        elif not ocr_available:
            scanned_alert = [
                "",
                f"> **⚠ SCANNED DOCUMENT — OCR NOT INSTALLED — {pct}% OF PAGES UNREADABLE**",
                ">",
                f"> This document (`{filename}`) is primarily composed of scanned images. "
                f"OCR software is not installed, so text from scanned pages could not be extracted.",
                ">",
                "> **To enable OCR for future runs:**",
                "> - **Mac:** Open Terminal and run: `brew install tesseract` — then restart AI Ready",
                "> - **Windows:** Download Tesseract from github.com/tesseract-ocr/tesseract — then restart AI Ready",
                ">",
                "> **Until OCR is installed:**",
                "> - Values on scanned pages are NOT present in this file",
                "> - Do not treat absence of a value as confirmation it does not exist",
                "> - Always verify against the original source document",
            ]
        else:
            scanned_alert = [
                "",
                f"> **⚠ SCANNED DOCUMENT WARNING — {pct}% OF PAGES ARE IMAGE-ONLY**",
                ">",
                f"> This document (`{filename}`) is primarily composed of scanned images. "
                f"Content from scanned pages is incomplete.",
                ">",
                "> Verify all values against the original source document.",
            ]

    # Tailor the AI instructions to the document type: only tax forms get the
    # Tax Line Index rule, so a medical/legal file doesn't reference a section
    # it doesn't have.
    type_rules = (
        _AI_PREAMBLE_TAX if (content_type == "Tax Form" and _has_tabular)
        else _AI_PREAMBLE_MEDICAL if (content_type == "Medical Document" and _has_tabular)
        else _AI_PREAMBLE_LEGAL if (_show_doc_index and meta.get("legal_index_reliable", False))
        else ""
    )
    if include_preamble:
        # Standalone file: fully self-contained (rules + notice in the file).
        preamble_blocks = [
            _global_rules(mask_mode, skip_all_masking) + type_rules,
            "",
            _LEGAL_DISCLAIMER,
        ]
    else:
        # Combined-output section: the global rules + legal notice live ONCE in
        # the combined part header. Markers let the per-file output (written
        # from the same masked text) re-insert the full blocks, so standalone
        # files lose nothing. Type-specific rules stay with their document.
        preamble_blocks = [_MARK_RULES + type_rules, "", _MARK_NOTICE]

    parts = [
        f"# Gold Master — {filename}",
        "",
        f"> Generated by AI Ready {VERSION} | {process_date}",
        "",
    ] + preamble_blocks + scanned_alert + [
        "",
        "---",
        "",
        "## ◈ Section 1 — Document Metadata",
        "",
        "| Field | Value |",
        "|---|---|",
    ] + meta_rows + [
        "",
        "### Extraction Validation",
        "",
        "| Check | Result |",
        "|---|---|",
    ] + validation_rows + tax_line_section + med_value_section + legal_index_section + condense_section + [
        "",
        "---",
        "",
        "## ◈ Section 2 — Audit Rules",
        "",
        "> **INTEGRITY STATEMENT — READ BEFORE USE**",
        ">",
        f"> 1. **Source Extraction (Section 3) is the authoritative record.** Text is extracted from `{filename}` at time of processing. Page layout may differ from the original due to PDF extraction, but page sequence and content are preserved.",
        f"> 2. **The SHA-256 hash ties this document to a specific version of `{filename}`.** Any modification to the source file produces a different hash.",
        "> 3. **This is a reference copy.** The original source document remains the authority for all legal, tax, and financial purposes.",
        f"> 4. **For AI analysis:** Cite Section 3 page anchors when referencing specific content (e.g., `[p.1]({anchor_example})`).",
        "",
        "---",
        "",
        "## ◈ Section 3 — Source Text Extraction",
        "",
        f"> Text extracted from `{filename}`, page by page. Layout may differ from the original PDF due to extraction, but page sequence and extracted text are preserved for audit review.",
        "",
        section3_md.strip(),
        "",
        "---",
        "",
    ] + ([_LEGAL_DISCLAIMER, ""] if include_preamble else []) + [
        f"*Gold Master generated by AI Ready {VERSION}*  ",
        f"*SHA-256: `{sha256_hash}`*",
    ]

    return "\n".join(parts)
def _term_to_regex(term: str) -> str:
    """
    Build a case-insensitive, whitespace-tolerant regex for a literal phrase so
    "315 Belles Landing" still matches "315   Belles  Landing". Internal spacing
    in the term is treated as "one or more whitespace"; everything else is literal.
    """
    tokens = re.split(r"\s+", term.strip())
    return r"\s+".join(re.escape(t) for t in tokens if t)


def _apply_custom_variables(text: str, variables: list[dict]) -> tuple[str, int, list[dict]]:
    """
    Apply custom Find/Replace rules to text.
    Returns (modified_text, total_count, per_term_stats).
    per_term_stats: list of {find, replace_with, count, action, overlap}
    """
    count = 0
    stats = []
    for var in variables:
        current = var.get("current", "").strip()
        masked = var.get("masked", "")          # intentionally not stripped — blank = delete
        if not current:
            continue
        # Match the term and any user-provided aliases (alternate spellings that
        # transcription tends to produce, e.g. "Connaker" for "Coniker"), each
        # tolerant of case and internal whitespace differences. Longest first so
        # "1317 Edgewater Drive" is consumed before the shorter "...Dr" (which
        # would otherwise leave a stray "ive" → "my Orlando addressive").
        terms = [current] + [a for a in var.get("aliases", []) if a and a.strip()]
        terms = sorted(set(terms), key=len, reverse=True)
        matches = 0
        for term in terms:
            pat = _term_to_regex(term)
            n = len(re.findall(pat, text, re.IGNORECASE))
            if n:
                text = re.sub(pat, masked, text, flags=re.IGNORECASE)
                matches += n
        count += matches
        action = "removed" if not masked.strip() else f"→ {masked}"
        # Overlap check: does this term look like something the built-in masker covers?
        overlap = _check_builtin_overlap(current)
        stats.append({
            "find": current,
            "replace_with": masked,
            "count": matches,
            "action": action,
            "overlap": overlap,
        })
    return text, count, stats
def _make_reg_rows(reg_entries: list) -> str:
    """Combined Source Registry table. Carries the full folder path (the hierarchy
    key) so every source document is traceable to its exact place in the tree —
    not just its bare filename. For flat (non-folder) runs the Folder Path equals
    the filename, so the table is unchanged in spirit."""
    rows = ["| Source ID | Source File | Folder Path | Pages | SHA-256 (first 16) | Anchor Prefix |",
            "|---|---|---|---:|---|---|"]
    for r in reg_entries:
        short_hash = r["sha256"][:16] + "…"
        folder_path = r.get("folder_path", r["filename"])
        rows.append(
            f"| {r['src_id']} | {r['filename']} | `{folder_path}` | {r['page_count']} | "
            f"`{short_hash}` | `{r['file_slug']}-page-NNN` |"
        )
    return "\n".join(rows)


def _carry_through_reason(ext: str) -> str:
    return CARRY_THROUGH_REASONS.get(
        ext, f"format {ext or '(none)'} not convertible to Markdown — original included for separate processing")


def _folder_group_key(rel: str) -> str:
    """One output per IMMEDIATE subfolder of the selected folder. `rel` is the
    browser's webkitRelativePath: `<selected>/<sub>/…/file.pdf`. Segment 0 is the
    selected root (constant across the upload); we group by segment 1 — the
    immediate child. A file sitting directly in the selected folder (2 segments)
    groups by its own filename → its own standalone output. A bare filename (no
    folder upload) returns the flat sentinel so behavior is unchanged."""
    segs = [s for s in rel.split("/") if s]
    if len(segs) <= 1:
        return "__flat__"
    return segs[1]


def _sanitize_group_base(name: str, used: set) -> str:
    """Filesystem-safe output stem from a subfolder (or standalone filename) name.
    Dedupes against already-used bases so two folders can't collide. Strips ONLY a
    real document extension — folder names are routinely date-prefixed with dots
    (e.g. `26.04 Cases cited in brief`, `25.09.30_Motion to seal`), so a blind
    splitext would mangle them to `26`/`25` and collide en masse."""
    stem = name
    low = name.lower()
    for ext in (".pdf", ".docx", ".pptx", ".txt", ".md", ".doc", ".ppt"):
        if low.endswith(ext):
            stem = name[: -len(ext)]
            break
    # Strip sanitization-artifact underscores, but KEEP a leading underscore the user
    # typed in the folder name (a common "sort to top" convention, e.g. `_APPEAL_...`).
    core = re.sub(r"[^A-Za-z0-9_-]+", "_", stem).strip("_")
    safe = (("_" if stem.startswith("_") else "") + core)[:60] or "group"
    base, n = safe, 2
    while base in used:
        base = f"{safe}_{n}"
        n += 1
    used.add(base)
    return base


def _simple_combined(combined_path: str, registry: list, raw_content: str,
                     timestamp: str, mask_mode: str, files_processed: int,
                     skip_all_masking: bool = False) -> None:
    """Fallback: write combined file directly without splitting."""
    reg_table = _make_reg_rows(registry)
    front_matter = _front_matter("ai-ready/combined", [
        ("files", files_processed),
        ("mask", _mask_label(mask_mode, skip_all_masking)),
        ("generated", datetime.now().strftime('%Y-%m-%d %H:%M:%S')),
        ("tool", f"AI Ready {VERSION}"),
    ])
    header = (
        f"# AI Ready — Combined Document\n\n"
        f"> **Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        f"> **Files combined:** {files_processed}\n"
        f"> **Mask mode:** {_mask_label(mask_mode, skip_all_masking)}\n\n"
        f"{_global_rules(mask_mode, skip_all_masking)}\n\n"
        f"{_LEGAL_DISCLAIMER}\n\n---\n\n"
        f"## Combined Source Registry\n\n"
        f"{reg_table}\n\n---\n\n"
        f"{_WORKING_NOTES_BLOCK}"
    )
    with open(combined_path, "w", encoding="utf-8") as f:
        f.write(front_matter)
        f.write(header)
        f.write(_APPEND_MARKER)     # top append zone — newest-first, add new docs on top
        f.write(raw_content)

_PART_TARGET = 1 * 1024 * 1024


def _split_gold_master(md: str, filename: str, file_slug: str, sha: str,
                       page_count, timestamp: str, gen_time: str,
                       mask_mode: str, name_prefix: str = "",
                       part_target: int | None = None) -> list:
    """Split one large file's Gold Master into ordered ~1 MB parts at PAGE
    boundaries (never mid-page), each a valid, self-identifying, AI-consumable
    `.md`. Part 1 carries the full preamble — metadata, Document Index, audit
    rules — so the whole file stays navigable from a single index; later parts
    carry a banner + their page range. Returns [{name, size, lo, hi}], or [] if the
    document has no page anchors to split on (caller keeps the monolith)."""
    pt = part_target or _PART_TARGET   # None → module global at call time (keeps tests)
    # The per-file .md leads with YAML front matter; strip it here and give each
    # part its OWN front matter (with part numbers) at the very top instead.
    if md.startswith("---\n"):
        _fm_end = md.find("\n---\n", 4)
        if _fm_end != -1:
            md = md[_fm_end + 5:].lstrip("\n")
    anchor_re = re.compile(r'<a id="' + re.escape(file_slug) + r'-page-(\d+)[^"]*"></a>')
    matches = list(anchor_re.finditer(md))
    if not matches:
        return []
    preamble = md[:matches[0].start()]            # header + Section 1/2 + §3 intro
    blocks = []                                    # (page_num, text) per page
    for i, m in enumerate(matches):
        end = matches[i + 1].start() if i + 1 < len(matches) else len(md)
        blocks.append((int(m.group(1)), md[m.start():end]))

    # Greedily pack whole pages into parts. Part 1's budget is reduced by the
    # preamble it must carry; a single page larger than the target gets its own part.
    groups, cur, cur_size = [], [], 0
    budget = pt - len(preamble.encode("utf-8"))
    for pg, txt in blocks:
        b = len(txt.encode("utf-8"))
        if cur and cur_size + b > (budget if not groups else pt):
            groups.append(cur)
            cur, cur_size = [], 0
        cur.append((pg, txt))
        cur_size += b
    if cur:
        groups.append(cur)

    total = len(groups)
    base = re.sub(r'[^A-Za-z0-9_-]+', '_', os.path.splitext(filename)[0])[:40].strip('_') or "file"
    parts = []
    for i, grp in enumerate(groups, 1):
        lo, hi = grp[0][0], grp[-1][0]
        body = "".join(t for _, t in grp)
        banner = (
            f"> **⚠ LARGE DOCUMENT — PROCESSED ON ITS OWN, SPLIT INTO {total} PART(S)**\n"
            f"> Source: `{filename}` · {page_count} pages · SHA-256 `{sha[:16]}…` · "
            f"mask mode: {_mask_label(mask_mode)}\n"
            f"> **This is Part {i} of {total}** — source pages **{lo}–{hi}**.\n"
            f"> This file was too large to fit one AI context, so it is delivered as "
            f"{total} parts. Upload **all parts together** for full coverage. The "
            f"**Document Index and audit rules are in Part 01**, mapping every element "
            f"to its source page.\n\n---\n\n"
        )
        part_fm = _front_matter("ai-ready/gold-master-part", [
            ("source", filename),
            ("sha256", sha),
            ("pages", f"{lo}-{hi} of {page_count}"),
            ("part", i),
            ("parts", total),
            ("mask", _mask_label(mask_mode)),
            ("tool", f"AI Ready {VERSION}"),
        ])
        if i == 1:
            text = part_fm + banner + preamble + body
        else:
            text = (part_fm
                    + f"# AI Ready — {filename} (Part {i} of {total})\n\n"
                    + banner
                    + f"## ◈ Section 3 (continued) — source pages {lo}–{hi}\n"
                    + body)
        name = f"AI_Ready_{timestamp}_{name_prefix}{base}_Part_{i:02d}of{total:02d}.md"
        parts.append({"name": name, "text": text,
                      "size": len(text.encode("utf-8")), "lo": lo, "hi": hi})
    return parts

def _emit_combined_group(base_name: str, label: str, registry: list,
                         raw_content: str, timestamp: str, gen_time: str,
                         mask_mode: str, files_in_group: int,
                         part_target: int | None = None,
                         skip_all_masking: bool = False) -> tuple:
    """Combine ONE group's pre-assembled sections (joined by START FILE markers)
    into output `.md`(s), splitting into ~1 MB parts at file boundaries (never
    mid-document). `base_name` is the output stem — a sanitized subfolder name in
    folder mode, or `AI_Ready_<ts>` for a flat run. `label` names the group in
    headers (the folder it represents). Returns (primary_output_name, [part_info]).
    """
    PART_TARGET = part_target or _PART_TARGET   # None → module global at call time
    splits = re.split(r'(?=\n\n---\n\n# ===== START FILE: )', raw_content)
    raw_sections = [s for s in splits if s.strip()]

    # Parse failure → write a simple combined under the base name (never lose content)
    if not raw_sections:
        out_name = f"{base_name}.md"
        out_path = os.path.join(OUTPUTS_DIR, out_name)
        _simple_combined(out_path, registry, raw_content, timestamp, mask_mode, files_in_group,
                         skip_all_masking=skip_all_masking)
        size = os.path.getsize(out_path) if os.path.exists(out_path) else 0
        return out_name, [{"name": out_name, "src_range": label, "file_count": len(registry),
                           "size": size, "oversized": False, "group": label}]

    # Pack whole source documents into ~1 MB parts; an oversized single doc gets its own.
    grouped, current_group, current_size = [], [], 0
    for idx, section in enumerate(raw_sections):
        sec_bytes = len(section.encode("utf-8"))
        if sec_bytes > PART_TARGET:
            if current_group:
                grouped.append(current_group)
            grouped.append([idx])
            current_group, current_size = [], 0
        elif current_group and current_size + sec_bytes > PART_TARGET:
            grouped.append(current_group)
            current_group, current_size = [idx], sec_bytes
        else:
            current_group.append(idx)
            current_size += sec_bytes
    if current_group:
        grouped.append(current_group)

    needs_split = len(grouped) > 1
    total_parts = len(grouped)
    out_parts = []

    for part_idx, group in enumerate(grouped, start=1):
        part_registry = [registry[i] for i in group if i < len(registry)]
        part_sections = [raw_sections[i] for i in group if i < len(raw_sections)]
        src_ids = [r["src_id"] for r in part_registry]
        src_range = (f"{src_ids[0]}–{src_ids[-1]}" if len(src_ids) > 1
                     else (src_ids[0] if src_ids else "?"))
        oversized_part = (len(group) == 1 and
                          len(raw_sections[group[0]].encode("utf-8")) > PART_TARGET)

        part_fname = (f"{base_name}_Part_{part_idx:02d}of{total_parts:02d}.md"
                      if needs_split else f"{base_name}.md")
        part_path = os.path.join(OUTPUTS_DIR, part_fname)

        if needs_split:
            xref_rows = ["| Part | Files | Source Documents |", "|---|---|---|"]
            for pi, pg in enumerate(grouped, start=1):
                pg_reg = [registry[i] for i in pg if i < len(registry)]
                pg_ids = [r["src_id"] for r in pg_reg]
                pg_range = (f"{pg_ids[0]}–{pg_ids[-1]}" if len(pg_ids) > 1
                            else (pg_ids[0] if pg_ids else "?"))
                pg_names = ", ".join(r["filename"][:30] for r in pg_reg[:3])
                if len(pg_reg) > 3:
                    pg_names += f" + {len(pg_reg)-3} more"
                marker = " **← THIS FILE**" if pi == part_idx else ""
                xref_rows.append(f"| Part {pi} of {total_parts} | {pg_range} | {pg_names}{marker} |")
            xref_block = (
                f"\n> **Part {part_idx} of {total_parts}** — {src_range} — "
                f"{len(part_registry)} source document(s)\n"
                f"> All parts were processed together in the same AI Ready run.\n"
                f"> If information is not found here, check the other parts.\n"
                f"> Upload all parts together in Claude or ChatGPT for full coverage.\n>\n"
                f"> " + "\n> ".join(xref_rows) + "\n"
            )
        else:
            xref_block = ""

        oversized_notice = ""
        if oversized_part:
            oversized_notice = (
                f"\n> **⚠ LARGE SINGLE DOCUMENT** — This part contains one source document "
                f"that exceeds the {PART_TARGET/1024/1024:g} MB AI context target. Consider "
                f"uploading this file's individual `.md` output for targeted questions.\n"
            )

        front_matter = _front_matter("ai-ready/combined", [
            ("title", label),
            ("part", part_idx),
            ("parts", total_parts),
            ("files", len(part_registry)),
            ("mask", _mask_label(mask_mode, skip_all_masking)),
            ("generated", gen_time),
            ("tool", f"AI Ready {VERSION}"),
        ])
        header = (
            f"# AI Ready — {label}"
            f"{f' (Part {part_idx} of {total_parts})' if needs_split else ''}\n\n"
            f"> **Source folder:** `{label}`\n"
            f"> **Generated:** {gen_time}\n"
            f"> **Files in this part:** {len(part_registry)}"
            f"{f' of {files_in_group} in this folder' if needs_split else ''}\n"
            f"> **Mask mode:** {_mask_label(mask_mode, skip_all_masking)}\n"
            f"{xref_block}"
            f"{oversized_notice}\n"
            # The global AI rules + legal notice appear ONCE per part (each part is
            # uploaded on its own) instead of once per document — the per-document
            # sections carry a one-line pointer plus their type-specific rules.
            f"{_global_rules(mask_mode, skip_all_masking)}\n\n"
            f"{_LEGAL_DISCLAIMER}\n\n---\n\n"
            f"## Combined Source Registry"
            f"{f' (Part {part_idx} of {total_parts})' if needs_split else ''}\n\n"
            f"{_make_reg_rows(part_registry)}\n\n---\n\n"
            f"{_WORKING_NOTES_BLOCK if part_idx == 1 else ''}"
        )

        with open(part_path, "w", encoding="utf-8") as f_out:
            f_out.write(front_matter)
            f_out.write(header)
            # Append zone at the TOP (part 1, after the working notes, before the first
            # source) so newly added documents land on top — keeping the file newest-first.
            if part_idx == 1:
                f_out.write(_APPEND_MARKER)
            for section in part_sections:
                f_out.write(section)

        out_parts.append({
            "name": part_fname,
            "src_range": src_range,
            "file_count": len(part_registry),
            "size": os.path.getsize(part_path),
            "oversized": oversized_part,
            "group": label,
        })

    return out_parts[0]["name"], out_parts
